name: Reference Python Package

on:
  [push, pull_request]

jobs:
  tests:
    name: ANTLR AST tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        antlr-version: ['4.9.2']
    defaults:
      run:
        working-directory: source/openqasm

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Update pip
        run: python -mpip install --upgrade pip

      - name: Install ANTLR4
        working-directory: source/grammar
        run: curl -O https://www.antlr.org/download/antlr-${{ matrix.antlr-version }}-complete.jar

      - name: Install ANTLR4 Python runtime
        run: python -mpip install antlr4-python3-runtime==${{ matrix.antlr-version }}

      - name: Generate grammar
        working-directory: source/grammar
        run: java -Xmx500M -jar antlr-${{ matrix.antlr-version }}-complete.jar -o ../openqasm/openqasm3/antlr -Dlanguage=Python3 -visitor qasm3.g4

      - name: Install Python packages for AST
        run: python -mpip install -r requirements.txt -r requirements-dev.txt

      - name: Build package
        run: python -mpip install -e .[all]

      - name: Check format
        run: black --check --diff openqasm3 tests

      - name: Check style
        run: pylint openqasm3 tests

      - name: Run tests
        run: pytest -vv --color=yes tests

  docs:
    name: Documentation build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source/openqasm
    strategy:
      fail-fast: false
      matrix:
        antlr-version: ['4.9.2']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Update pip
        run: python -mpip install --upgrade pip
      - name: Install ANTLR4
        working-directory: source/grammar
        run: curl -O https://www.antlr.org/download/antlr-${{ matrix.antlr-version }}-complete.jar
      - name: Install ANTLR4 Python runtime
        run: python -mpip install antlr4-python3-runtime==${{ matrix.antlr-version }}
      - name: Generate grammar
        working-directory: source/grammar
        run:
          java -Xmx500M -jar antlr-${{ matrix.antlr-version }}-complete.jar -o ../openqasm/openqasm3/antlr -Dlanguage=Python3 -visitor qasm3.g4
      - name: Install Python packages for AST
        run: python -mpip install -r requirements.txt -r requirements-dev.txt
      - name: Build package
        run: python -mpip install -e .[all]
      - name: Build documentation
        working-directory: source/openqasm/docs
        run: make html
      - uses: actions/upload-artifact@v2
        with:
          name: openqasm3-html-documentation
          path: source/openqasm/docs/_build/html/*
          if-no-files-found: error
